### ISSUE TITLE
/templist issues[BUG]

### ISSUE THREAD

**Issue by SodiumShine** [ElgarL/GroupManager#1]
**Describe the bug**
Using /templist without any parameters causes console errors but no user feedback

**To Reproduce**
Have permissions to type /templist
Do so

**Expected behavior**
To be told there are no temp permissions and not to freakout on the console

**Please complete the following information:**
 - OS: Windows 10
 - spigot/craftbukkit version: 1.16.1
 - Plug-in version 2.3

**Additional context**

> 01.07 23:12:38 [Server] Server thread/INFO Ming issued server command: /templist
01.07 23:12:38 [Server] Server thread/WARN java.lang.NullPointerException
01.07 23:12:38 [Server] Server thread/WARN at org.anjocaido.groupmanager.commands.TempList.parseCommand(TempList.java:52)
01.07 23:12:38 [Server] Server thread/WARN at org.anjocaido.groupmanager.commands.BaseCommand.onCommand(BaseCommand.java:85)
01.07 23:12:38 [Server] Server thread/WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
01.07 23:12:38 [Server] Server thread/WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
01.07 23:12:38 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:747)
01.07 23:12:38 [Server] Server thread/WARN at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1702)
01.07 23:12:38 [Server] Server thread/WARN at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1545)
01.07 23:12:38 [Server] Server thread/WARN at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
01.07 23:12:38 [Server] Server thread/WARN at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
01.07 23:12:38 [Server] Server thread/WARN at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
01.07 23:12:38 [Server] Server thread/WARN at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
01.07 23:12:38 [Server] Server thread/WARN at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
01.07 23:12:38 [Server] Server thread/WARN at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
01.07 23:12:38 [Server] Server thread/WARN at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
01.07 23:12:38 [Server] Server thread/WARN at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:941)
01.07 23:12:38 [Server] Server thread/WARN at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:934)
01.07 23:12:38 [Server] Server thread/WARN at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
01.07 23:12:38 [Server] Server thread/WARN at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:918)
01.07 23:12:38 [Server] Server thread/WARN at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:850)
01.07 23:12:38 [Server] Server thread/WARN at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
01.07 23:12:38 [Server] Server thread/WARN at java.lang.Thread.run(Thread.java:748)

**Comment by ElgarL** [comment]
Fixed and updatedfv2.3 download, Thanks.
