### ISSUE TITLE
Paper 1.13.2 - Wrong API

### ISSUE THREAD

**Issue by BobbyMere** [ElgarL/GroupManager#10]
on paper 1.13.2 it fails to load https://hasteb.in/igidoqik.sql

ubuntu 18.04
paper 1.13.2 
v2.4

**Comment by ElgarL** [comment]
Fixed in the 2.5-SNAPSHOT [](https://github.com/ElgarL/GroupManager/releases/tag/v2.5-SNAPSHOT)
