### ISSUE TITLE
Owner can add owner ingame

### ISSUE THREAD

**Issue by meganizer** [ElgarL/GroupManager#102]
**Description**
(Since the newest update minecraft 1.20.1 and the newest group manager(3.2) i found that and owner can /manuadd player owner another player, in the previous version of minecraft (1.19.2) with group manager (3.0) this was not possible and can only be done from the console)

**Steps to reproduce**
1. Go to 'Minecraft server as owner'
2. execute '/manuadd playername Owner'
3. 'See that the player is indeed an Owner'

**Expected behavior**
(There should be an error "The destination group can't be the same as yours, nor higher.".)

**Please complete the following information:**
 - OS: Ubuntu 22.04LTS
 - Paper/Spigot version: Spigot 1.20.1
 - Plugin version V3.2

**Additional context**
I have set the config.yml to not let op override on both versions

**Comment by ElgarL** [comment]
By default the Owner group has the `*` wildcard and as such gains all default permissions including `groupmanager.op`.
With this permission the Owner group can promote players to the same group. It will not work for a group like `Moderator` which has no wildcard. If you are in the `Moderator` group you can not promote to the same group.
The opOverride in the config does not affect the `groupmanager.op` permission, it only controls if all op players are treated as having all permissions.

**Comment by meganizer** [comment]
We had that it did not operate that way since the GroupManager that came with 1.16.1 and all the updates after until this update i thought it was supposed to do it this way, is there any way i can get this functionallity back like removing groupmanager.op rights somewhere?

**Comment by ElgarL** [comment]
You can negate `- -groupmanager.op` in the Owner group

**Comment by meganizer** [comment]
I also noticed if a moderator temporarly has /op player while opOverrides: false than the moderator can add themselfs to the owner group this also was not possible before, i will set - -groupmanager.op to owner now

**Comment by ElgarL** [comment]
> I also noticed if a moderator temporarly has /op player while opOverrides: false than the moderator can add themselfs to the owner group this also was not possible before, i will set - -groupmanager.op to owner now

Yes, while opOverride ensures an op has all permissions (registered and not), when false the op player will still gain all registered permissions.

**Comment by meganizer** [comment]
I will have to create a new group in between my current groups to solve this issue the way it works for this server between Admin and Owner thanks for looking into this issue with me :)
