### ISSUE TITLE
Wilcard permissions not working, or rarely.

### ISSUE THREAD

**Issue by pokameni** [ElgarL/GroupManager#104]
**Description**
Any plugin with wilcard permissions nodes will probably not work at all using GroupManager. I've found also ShopGui+ and ChatEmojis to say somes.

**Steps to reproduce**
- Add any plugin with wilcard permission like ShopGui+ or ChatEmoji,
- Add wilcard permission
- Try yourself

**Expected behavior**
- Permission should work and grant access the player 

**Screenshots**
![image](https://github.com/ElgarL/GroupManager/assets/88514584/8624dbdc-b9c9-4731-9645-626cc44dab06)
- I just tried to say `:(`, i had already the wilcard permission), not working, then i opped myself and added classic permission), and deopped. working well. but not fast at all. SAME ERROR WITH OTHER PLUGINS.

**Please complete the following information:**
 - Self Hosted on W11 Pro
 - Paper version git-Paper-169 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b4e3b3d)
 - GroupManager 3.2

**Additional context**
-

**Comment by ElgarL** [comment]
Wildcard permissions are not supported in Bukkit. As such only plugins which check permissions via Vault or directly with the permission plugin can use and support wildcards. GroupManager handles wildcard permissions but only if the plugin itself correctly supports them.
