### ISSUE TITLE
Allow you to organize the tablist by rank for 1.21.2+

### ISSUE THREAD

**Issue by Budderman18** [ElgarL/GroupManager#107]
**Is your feature request related to a problem? Please describe.**
1.21.2 added the ability to sort the tablist by any order, rather than being stuck in just alphabetical order. 

**Describe the solution you'd like**
Be able to sort the tablist, either automatically using the already determined hierarchy or individually by rank (useful for servers with multiple rank hierarchies).

**Additional context**
There is a bukkit API method for it (player#setPlayerListOrder(int)) so it should not be too difficult.

**Comment by ElgarL** [comment]
Tab list ordering has no place in a permissions plugin. All GroupManager does is provide permissions/groups. You should look at a tab ordering plugin for this feature.
