### ISSUE TITLE
Bug on latest release

### ISSUE THREAD

**Issue by ElytraPvP** [ElgarL/GroupManager#11]
Heya, I just updated from an old patch of group manager to the latest release, and whenever i log on i see this text

>.... [13:27:25 ERROR]: [global] TaskChain Exception on me.glaremasters.guilds.guild.GuildHandler$$Lambda$4630/1027843257: java.lang.IllegalAccessError: tried to access field org.anjocaido.groupmanager.GroupManager.BukkitPermissions from class net.milkbowl.vault.permission.plugins.Permission_GroupManager
>.... [13:27:25 ERROR]: [global] Current Action Index was: 0
>.... [13:27:25 WARN]: java.lang.Exception: java.lang.IllegalAccessError: tried to access field org.anjocaido.groupmanager.GroupManager.BukkitPermissions from class net.milkbowl.vault.permission.plugins.Permission_GroupManager
>.... [13:27:25 WARN]: at me.glaremasters.guilds.libs.taskchain.TaskChain.handleError(TaskChain.java:1203)
>.... [13:27:25 WARN]: at me.glaremasters.guilds.libs.taskchain.TaskChain.access$600(TaskChain.java:57)
>.... [13:27:25 WARN]: at me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1320)
>.... [13:27:25 WARN]: at me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
>.... [13:27:25 WARN]: at me.glaremasters.guilds.libs.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187)
>.... [13:27:25 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>.... [13:27:25 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>.... [13:27:25 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [13:27:25 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [13:27:25 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [13:27:25 WARN]: Caused by: java.lang.IllegalAccessError: tried to access field org.anjocaido.groupmanager.GroupManager.BukkitPermissions from class net.milkbowl.vault.permission.plugins.Permission_GroupManager
>.... [13:27:25 WARN]: at net.milkbowl.vault.permission.plugins.Permission_GroupManager.playerAdd(Permission_GroupManager.java:132)
>.... [13:27:25 WARN]: at net.milkbowl.vault.permission.Permission.playerAdd(Permission.java:185)
>.... [13:27:25 WARN]: at me.glaremasters.guilds.guild.GuildHandler.lambda$null$16(GuildHandler.java:770)
>.... [13:27:25 WARN]: at java.util.ArrayList.forEach(ArrayList.java:1257)
>.... [13:27:25 WARN]: at me.glaremasters.guilds.guild.GuildHandler.lambda$addPerms$17(GuildHandler.java:768)
>.... [13:27:25 WARN]: at me.glaremasters.guilds.libs.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
>.... [13:27:25 WARN]: at me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
>.... [13:27:25 WARN]: ... 7 more

Thats all aha. didn't happen on the very old version but anyway hope you see this, so glad this plugin is being brought back up!

**Comment by ElgarL** [comment]
Some context here, or some way to replicate this error please.

**Comment by ElgarL** [comment]
I have submitted a pull request to Vault to fix this issue.

**Comment by ElgarL** [comment]
I've updated the 2.5-SNAPSHOT to retain backward compatibility until Vault updates.
You are safe to update.

https://github.com/ElgarL/GroupManager/releases/tag/v2.5-SNAPSHOT
