### ISSUE TITLE
Request: Option To Remove Offline Names

### ISSUE THREAD

**Issue by BobbyMere** [ElgarL/GroupManager#14]
I know I've already inquired about this on discord but I never got a definitive answer, and this is a more calming platform to converse ideas. 

I understand that the tab auto fill to show all names is an intended feature but I'm requesting an option to only show names that are currently online.

**Comment by ElgarL** [comment]
I added a new config setting to enable/disable this functionality (default enabled).
When enabled it will obey the mantogglevalidate state.

Please test its fully working http://palmergames.com/libs/GroupManager.jar

**Comment by ElgarL** [comment]
I'll assume this is working. I did test myself too.
