### ISSUE TITLE
[BUG] Groupmanager Not Working (has error)

### ISSUE THREAD

**Issue by LegoCraftNW** [ElgarL/GroupManager#16]
**Groupmanager not working**
I get this error when I enter the server: https://hastebin.com/hehatuzili.cs

the plugin does not work. so I cannot give groups: https://hastebin.com/cebejixibi.bash

**Please complete the following information:**
 - OS: Ubuntu Linux 18.04 LTS
 - git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
 - plugin version v2.5

**Comment by ElgarL** [comment]
You can ignore the error, it won't stop anything working and its fixed in the 2.6 SNAPSHOT.

You can get a pre-release at [http://palmergames.com/libs/GroupManager.jar](http://palmergames.com/libs/GroupManager.jar)
