### ISSUE TITLE
[BUG] Ranks disappearing? 

### ISSUE THREAD

**Issue by jayjaffacakes** [ElgarL/GroupManager#19]
**Describe the bug**
Everytime I go to create ranks they wont appear in groups.yml . When ever I need to restart or reload plugins the new ranks will disappear. I do create ranks while im on my server with the commands /mangadd and the other ones

**To Reproduce**
Create a rank then /reload or restart from console.

**Expected behavior**
Ranks to stay and for them to appear in the file. 

**Please complete the following information:**
 - OS: Windows 10 with Java 8
 - spigot 1.16.1
 - Plug-in version v2.5

**Comment by ElgarL** [comment]
Do a /mansave
GroupManager is memory resident and saves on a schedule (10 minutes), unless you /mansave to force it to save changes.

**Comment by jayjaffacakes** [comment]
ty! that fixed it :)
