### ISSUE TITLE
[BUG] Dynmap Error caused by GroupManager

### ISSUE THREAD

**Issue by UnweildedBlade** [ElgarL/GroupManager#2]
**Describe the bug**
Dynmap will have an Error with group managers class system

**To Reproduce**
1. Have both dynmap and Groupmanager installed
2. Run server
3. See Error

**Expected behavior**
Both plugins running :)

**Please complete the following information:**
 - OS:  Windows 10
 - spigot/craftbukkit version: 1.16.1
 - Plug-in version [e.g. v2.2

**Additional context**

ERROR Error occurred while enabling dynmap v3.1-beta-1-367 (Is it up to date?)
03.07 02:53:47 [Server] INFO java.lang.IncompatibleClassChangeError: Expecting non-static method 'org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder org.anjocaido.groupmanager.GroupManager.getWorldsHolder()'

**Comment by UnweildedBlade** [comment]
I know this doesnt pertain much to you as it does to dynmap. And Ive sent them a bug as well. I just want it to be know there is a compatibility issue between your mods :)

**Comment by ElgarL** [comment]
Thank you for the report. However, this has already been fixed in the current release build (v2.3).
