### ISSUE TITLE
[BUG] Permission Mirroring Issue - v2.7

### ISSUE THREAD

**Issue by Lurick73** [ElgarL/GroupManager#28]
**Describe the bug**
When a user travels between the overworld and the Nether or End they lose their permissions and are put in the default group and permissions are not mirrored between them.

**To Reproduce**
1. Upgrade to 2.7 (latest release)
2. Have a user travel between the default world and the nether or end.
3. Check the user's group and they will be in the default group instead of the regular group they are in when in the overworld

**Expected behavior**
Permissions and groups should be synced between worlds.

**Please complete the following information:**
 - OS: [Windows 10]
 - spigot: [1.16.2]
 - Plug-in version [2.7]

**Additional context**
This issue is not present in 2.5 or 2.6 on the same server (same 1.16.2 version as well). No log messages but doing /manulistp for a user shows Default instead of Builder or anything else for the sub-worlds. This might be related to the all_unnamed_worlds section in the config and I'll edit or post a comment if I can narrow it down.

**Comment by ElgarL** [comment]
Delete your config.yml. There were a coupe of new nodes added and yours is erroring.
