### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by BleuBleue** [ElgarL/GroupManager#3]
Hello. I request to add the RGB support ! like &#00FFCC

**Comment by ElgarL** [comment]
An interesting request and I''m open to a discussion. However, I don't think it is appropriate for GM to do anything with this as
any translation should be handled by the relevant chat plug-in.
GM will hold and supply anything you choose to place in the prefix/Suffix, including RGB colour codes. What any plug-in decides to do with that after is up to the plug-in in question.

**Comment by BleuBleue** [comment]
Hello, excuse my very bad English, I am French. In addition I explain to you that I would like GM to be able to accept that we use the color codes added in 1.16.1 (the Hex color / RGB) For the translations, it is another player who asked you ahah!

**Comment by ElgarL** [comment]
GM Will support any text/codes you want to put in. Your chat plug-in is the plug-in that handles them.
