### ISSUE TITLE
PlaceholderAPI Support

### ISSUE THREAD

**Issue by itslukemango** [ElgarL/GroupManager#51]
**Is your feature request related to a problem? Please describe.**
(A clear and concise description of what problem you are experiencing. E.g. I'm always frustrated when [...])
On our scoreboard and chat (when you hover over names in chat), we want the ability to show subgroups which currently isn't possible. 

**Describe the solution you'd like**
(A clear and concise description of what you want to happen.)
We'd like GM to add direct support for PAPI

**Additional context**
(Add any other context or screenshots about the feature request here.)
Please make sure subgroups, groups return the name (%groupmanager_group%) aswell as possibly something like %groupmanager_perm_(perm)% could return true/false if the player does/doesn't have the permission.
For example, if I have access to essentials.fly and I have %groupmanager_perm_essentials.fly% on a scoreboard, it'd say "true".

For subgroups, it could be more complicated as players can have more than one, a fix would be having a priority feature in groups.yml, the highest (0 or max java int, depending on which you choose) would show in %groupmanager_subgroup%. (If this doesn't make sense, let me know, I can probably explain it a little better)

**Comment by ElgarL** [comment]
- Add PAPI support...
        %groupmanager_group%, %groupmanager_allgroups%, %groupmanager_subgroups%,
        %groupmanager_user_prefix%, %groupmanager_user_suffix%,
        %groupmanager_group_prefix%, %groupmanager_group_suffix%,
        PAPI permission checks - %groupmanager_perm_permission.here%
