### ISSUE TITLE
Vicky5

### ISSUE THREAD

**Issue by balasarathi** [ElgarL/GroupManager#61]
**Description**
(A clear and concise description of what the bug is.)

**Steps to reproduce**
4. See an error

**Expected behavior**
(A clear and concise description of what you expected to happen.)

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Please complete the following information:**
 - OS: [e.g. Windows 10]
 - Paper/Spigot version: [e.g. 1.15.2, 1.16.3]
 - Plugin version [e.g. v2.8]

**Additional context**
Add any other context about the problem here, **including any error logs**.

**Comment by ElgarL** [comment]
I'm going to assume this was a mistake as there is nothing but the reporting template here.
