### ISSUE TITLE
Delete Inactive Users

### ISSUE THREAD

**Issue by hellosarina** [ElgarL/GroupManager#63]
With a large amount of players passing through on some servers, this causes group manager to create user data for each individual player. I think a good feature to have would be the ability to delete inactive user data after X amount of days. For example, if a player has been inactive for over 100 days you can "purge" them from your user file. 

Ex command: /manuclean <days> <group>

This would also clean up the users.yml file resulting in less lag in the console.

**Comment by ElgarL** [comment]
Would this be better as a config setting?
If set in the config it could automatically prune old accounts at startup.

**Comment by hellosarina** [comment]
That would work as well! An automatic way to purge old accounts after a
certain time limit  would be great!

**Comment by ElgarL** [comment]
A very early beta build (if you are willing to test it) - Don't use on a live server yet as this version has MANY changes and is very untested.

http://palmergames.com/libs/GroupManager.jar
Delete your old config and allow GM to create a new one.

> v3.0:
    - Performance improvements.
    - Version update checking now works correctly.
    - Add a purge for old users (runs at server start).
        New users will gain a 'lastplayed' variable upon joining.
        This value will be updated each time they join.
        If they do not log in for (default 90 days) their data will be deleted.
        Manually created users who have never joined will not be deleted.
        Users created with older versions of GroupManager who never log in will not be deleted.
        To protect specific accounts from deletion set the lastplayed variable to '0'.

**Comment by hellosarina** [comment]
I will go ahead and test this out in our practice server!

**Comment by ElgarL** [comment]
You may want to update. I changed the way this works (slightly). It now uses the servers last seen to test if the player needs to be purged. 
This will be more accurate and can in fact remove old players from before this feature was added.
It will also result in less data updates so less change of a conflict further down the road when SQL is added.
You can still protect players from being purged by adding a lastplayed variable set to zero (0).

**Comment by ElgarL** [comment]
I'm closing this as its currently in the experimental branch.
