### ISSUE TITLE
[resolved] Player rank is not saved

### ISSUE THREAD

**Issue by CodesGamesYTB** [ElgarL/GroupManager#70]
When I execute the "/manload" command or when I restart /reload my server, the players have the default rank.

**Comment by ElgarL** [comment]
With no details I can only assume you have incorrect mirroring.

**Comment by CodesGamesYTB** [comment]
Issue resolved:

I moved the "GroupManager" folder to my desktop and performed a server restart to get "GroupManager" to recreate the folder. I then manually replaced my "GroupManager" folder that I had put on my desktop in place of the folder that was recreated.
