### ISSUE TITLE
no players have perms?

### ISSUE THREAD

**Issue by saintblair11** [ElgarL/GroupManager#71]
https://www.youtube.com/watch?v=_D_3kusyuJI

video guide ive watched, read alot but still cant seem to make it so anyone has permissions unless there an op

when ever moving causes alot of player event issues unless op.
[ERROR.LOG](https://github.com/ElgarL/GroupManager/files/6333326/ERROR.LOG)

[globalgroups.txt](https://github.com/ElgarL/GroupManager/files/6333343/globalgroups.txt)
[groups.txt](https://github.com/ElgarL/GroupManager/files/6333345/groups.txt)

file extension changed to .txt to be uploadable

paper spigot 1.16.5
GroupManager+ [v3.3]

**Comment by l1ttleO** [comment]
GroupManager+ is not made by us, GroupManager+ is an old and unsupported fork. Please download GroupManager from http://palmergames.com/libs/GroupManager.jar
