### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by s7an1slaw** [ElgarL/GroupManager#73]
Hello, why when I give a permission to the default or any group and when I use / manload or restart the server and permissions they do not exist.

**Comment by ElgarL** [comment]
/manload tells GM to reload the files from disc. If you added the permissions manually and they don't appear after a manload you likely broke the files with incorrect editing.
Always check your latest.log on the server for errors.

**Comment by s7an1slaw** [comment]
I deleted the plugin folder and started adding them one by one and it worked.
