### ISSUE TITLE
Tab Prefix Not Going Away

### ISSUE THREAD

**Issue by yourlocalvirgo** [ElgarL/GroupManager#75]
I had installed GroupManager and set up some group prefixes for my tab list, however, when I uninstalled GroupManager, the tablist prefixes stayed and I have no idea how to get rid of them. Please help.

**Comment by ElgarL** [comment]
If you uninstalled GM and you still have prefixes, its not GM adding them. Groupmanager only provides data upon request to other plugins and Bukkit.
