### ISSUE TITLE
Transfer of Spigot GroupManager page

### ISSUE THREAD

**Issue by Xadzkon** [ElgarL/GroupManager#8]
Hello,

I was previously compiling GroupManager to the latest version of Spigot for my own needs and I originally even planned add new features but I no longer have the time and effort to even update it. Fortunately, you have came back. I am the owner of the [GroupManager page on Spigot](https://www.spigotmc.org/resources/groupmanager.38875/). That page is the number one result that comes up when Googling "GroupManager".

Please tell me your Spigot username, and I will open a support request to transfer the plugin page to you.

I also have a messy GitHub repository GroupManager/GroupManager, I can transfer that to you as well, so you can redirect users to here.

Cheers.

**Comment by ElgarL** [comment]
Thanks. I'm ElgarL on everywhere ;)

July 28, 2020 7:23 PM, "Xadzkon" <notifications@github.com (mailto:notifications@github.com?to=%22Xadzkon%22%20<notifications@github.com>)> wrote:
	Hello, 

	I was previously compiling GroupManager to the latest version of Spigot for my own needs and I originally even planned add new features but I no longer have the time and effort to even update it. Fortunately, you have came back. I am the owner of the GroupManager page on Spigot (https://www.spigotmc.org/resources/groupmanager.38875/). That page is the number one result that comes up when Googling "GroupManager". 

	Please tell me your Spigot username, and I will open a support request to transfer the plugin page to you. 

	I also have a messy GitHub repository GroupManager/GroupManager, I can transfer that to you as well, so you can redirect users to here. 

	Cheers.

**Comment by Xadzkon** [comment]
The resource page has now been moved over to your Spigot account.

**Comment by ElgarL** [comment]
Thanks. I'll close this ticket for now.
