### ISSUE TITLE
Scope disconnected players.

### ISSUE THREAD

**Issue by AlzheTV** [ElgarL/GroupManager#93]
**Is your feature request related to a problem? Please describe.**
No, not on this plugin, but yes, caused by this plugin.
This plugin does not check the permissions of disconnected/logging out players, so you can't hide the logout message with one of the more popular plugins ([EssentialsX - Issue here](https://github.com/EssentialsX/Essentials/issues/1108)).

**Describe the solution you'd like**
The possibility for GroupManager to manage, target disconnected players. I also assume as said in the above issue that it will require Vault.

**Additional context**
The two three reasons I use GM instead of another permission plugin is that I am used to using this permission plugin since 1.8. And that despite this little issue that doesn't bother me that much, I admit that I would love to see this feature. Moreover, it is very easy to use and understand.

Oh and I'm not a Java developer, or even any developer... Otherwise I would have liked to contribute.

I'm really sorry I don't have any code to share. 🙄❤️

Hopefully this feature request will be applied soon! :D

**Comment by ElgarL** [comment]
Sorry I don't understand this ticket. A Player logging out has the same permissions as he has when connected. At the point of him disconnecting he still has those same permissions. I have posted on the EssentialsX ticket for clarification too.

**Comment by ElgarL** [comment]
I have done some digging and this is clearly an Essentials bug. Vault/GroupManager both report the correct permissions for a player joining/leaving. In both instances the Player is online with a valid Player object (before the join message is sent). Essentials is, for some reason, not clearing the join message.
![default player](https://user-images.githubusercontent.com/898636/189643519-d5f81013-9c36-4382-8d44-4a4374d6a5f9.PNG)
![op with all perms](https://user-images.githubusercontent.com/898636/189643529-b44b758a-0b50-4bfa-8831-20be81910da4.PNG)

**Comment by ElgarL** [comment]
I'm going to close this as it is an Essentials bug. I've given them the information about it, where the bug is, and how to fix it.
https://github.com/EssentialsX/Essentials/issues/1677#issuecomment-1243613547

**Comment by ElgarL** [comment]
I have pushed a fix to GroupManager pre-release. This will fix the compatibility issue with EssentialsX silent vanish.
