### ISSUE TITLE
Excuse me, I edited it wrong. .

### ISSUE THREAD

**Issue by 3154311518** [ElgarL/GroupManager#96]
Excuse me, I edited it wrong. .

**Comment by ElgarL** [comment]
You need Java 11 to run GM on 1.8.8 Spigot. Newer Java versions prevent class injection of the drivers.

**Comment by 3154311518** [comment]
> You need Java 11 to run GM on 1.8.8 Spigot. Newer Java versions prevent class injection of the drivers.

ok thanks for your help
